catalog/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [


    url(r'^m_list/$',
        views.MediaBotStateListView.as_view(),
        name='media_list'),

    url(r'^m_detail_short/(?P<pk>\d+)/$',
        views.MediaBotStateShortDetailView.as_view(),
        name='media_detail_short'),

    url(r'^m_detail_long/(?P<pk>\d+)/$',
        views.MediaBotStateLongDetailView.as_view(),
        name='media_detail_long'),

]

fasttrack_structured/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from django.urls import reverse_lazy
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^$', RedirectView.as_view(url=reverse_lazy('admin:index'))),
    url(r'^admin/', admin.site.urls),
    url(r'^cat/', include('catalog.urls', namespace='catalog')),
    url(r'^state_templates/', include('state_templates.urls', namespace='state_templates')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

state_templates/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [


    url(r'^template_update/(?P<pk>\d+)/$',
        views.StateTemplateView.as_view(),
        name='template_update'),

]

catalog/models/media.py
from django.db import models


class Media(models.Model):
    """
    Модель медиаконтента
    """
    title = models.CharField(max_length=1000, blank=True, null=True)
    author = models.CharField(max_length=1000, blank=True, null=True)
    teaser = models.TextField(max_length=1000, blank=True, null=True)
    summary = models.TextField(blank=True, null=True)
    full_version = models.TextField(blank=True, null=True)
    cover_media = models.URLField(blank=True, null=True)

core/models.py
from django.db import models

# Create your models here.

state_templates/models.py
from django.db import models


class BotStateTemplate(models.Model):
    """
    Шаблоны для вьюх. Имеют названия (соответствует классам вьюх),
    и содержат контент для всех платформ.
    """
    view_name = models.CharField(max_length=100)
    telegram_template = models.TextField()
    facebook_template = models.TextField()
    viber_template = models.TextField()

    def __str__(self):
        return self.view_name

catalog/views/media.py
# Create your views here.
import json
from django.http import JsonResponse
from django.views.generic import ListView, DetailView
from django.template import Context, Template
import jsonpickle
from ..models import Media
from state_templates.models import BotStateTemplate
# from sending.state_objects import BotState, TGTextMessage


class BotStateTemplateResponseMixin(object):
    """
    Миксин, который достает шаблон, соответствующий вьюхе,
    и рендерит Json с этим шаблоном.
    """
    def get_context_data(self, **kwargs):
        """
        если запрос сделан с GET-параметром postback_prefix, добавить его
        в контект. И тогда в шаблонах он будет добавлен ко всем
        генерируемым урлам.

        Например, урл /cat/media_list/ превратится
        в /some/prefix/cat/media_list/)
        """
        context = super().get_context_data(**kwargs)
        context['postback_prefix'] = self.request.GET.get('postback_prefix', '')
        return context


    def render_to_response(self, context, **response_kwargs):
        """
        Получаем шаблон, имя которого соответствует имени текущего класса,
        рендерим с контекстом джанго, возвращаем в json
        """
        template_string = BotStateTemplate.objects.get(
            view_name=self.__class__.__name__
        ).facebook_template

        rendered = Template(template_string).render(Context(context))

        return JsonResponse(json.loads(rendered))


class MediaBotStateListView(BotStateTemplateResponseMixin, ListView):
    """
    представление списка объектов
    """
    model = Media


class MediaBotStateShortDetailView(BotStateTemplateResponseMixin, DetailView):
    """
    короткое представление одного объекта
    """
    model = Media


class MediaBotStateLongDetailView(BotStateTemplateResponseMixin, DetailView):
    """
    длинное представление одного объекта
    """
    model = Media

state_templates/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
from django.urls import reverse
from django.views.generic import DetailView, UpdateView
from state_templates.models import BotStateTemplate


class StateTemplateView(UpdateView):
    model = BotStateTemplate
    fields = ('view_name', 'facebook_template')
    template_name = 'state_templates/state_template_update.html'

    def form_valid(self, form):
        return HttpResponse('Редактировать этот шаблон запрещено.')

    def get_success_url(self):
        return reverse('state_templates:template_update', kwargs={
            'pk': self.object.pk
        })

templates/state_templates/state_template_update.html
{% load widget_tweaks staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <script src="{% static 'libs/ace/ace.js' %}"></script>
    <script src="{% static 'libs/ace/theme-monokai.js' %}"></script>
    <script src="{% static 'libs/ace/mode-json.js' %}"></script>
    <script src="{% static 'libs/ace/mode-text.js' %}"></script>
    <script src="{% static 'libs/jquery-ace.min.js' %}"></script>

</head>
<body>
<br/>
<br/>
<br/>
<div class="container">
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            {% render_field form.view_name class+='form-control' %}
        </div>
        <div class="form-group">
            {% render_field form.facebook_template class+='form-control' rows=25 %}
        </div>
        <button class="btn btn-primary" type="submit">Сохранить</button>
    </form>
</div>

<script>
    $('#id_facebook_template').ace({ theme: 'monokai', lang: 'json' })
</script>
</body>
</html>